# Site Settings
baseurl: ""

# Features Setting
# Turn subpages on or off
publications: True
presentations: False
blog: False
projects: False

# Language of the website
lang: en

# Search engine optimization settings
title: Rafael Bailon-Ruiz
tagline: If it's not on the internet, it doesn't exist
description: Rafael Bailon-Ruiz personal website
author: Rafael Bailon-Ruiz
twitter:
  username: rafael1193
  card: Rafael Bailon-Ruiz's personal website
logo: /assets/img/smile.png
social:
  name: Rafael Bailon-Ruiz
  links:
    - https://mastodon.rafaelbailon.com
    - https://github.com/rafael1193
locale: en_US

# Page Settings
theme_settings:
  title: "Rafael Bailon-Ruiz"

  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  awards_title: AWARDS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag', 'jekyll-sitemap']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: ieee
  locale: en
  last_name: Bailon-Ruiz
  first_name: [Rafael, R.]
  sort_by: year,month
  order: descending,ascending

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
